MMMSearchObj.searches = [
{id:"au_yahoo",
type:"portals",
cc:"au",
name:"yahoo",
label:"yahoo.au",
url:"http://www.yahoo.au",
surl:"http://au.search.yahoo.com/search?p=",
desc:""},

{id:"au_ansearch",
type:"portals",
cc:"au",
name:"ansearch",
label:"ansearch.com.au",
url:"http://www.ansearch.com.au",
surl:"http://www.ansearch.com.au/search?s=all&a=all&cc=au&search=",
desc:""},

{id:"au_ebay",
type:"shopping",
cc:"au",
name:"ebay",
label:"ebay.au",
url:"http://www.ebay.com.au",
surl:"http://search.ebay.com.au/",
desc:""},

{id:"au_doorone",
type:"shopping",
cc:"au",
name:"doorone",
label:"doorone.au",
url:"http://doorone.com.au",
surl:"http://doorone.com.au/xFS?KW=",
desc:""},

{id:"au_ferret",
type:"shopping",
cc:"au",
name:"ferret",
label:"ferret.com.au",
url:"http://www.ferret.com.au",
surl:"http://www.ferret.com.au/search.asp?qu=",
desc:"Australian suppliers/products search"},

{id:"au_abc",
type:"news",
cc:"au",
name:"abc",
label:"abc.net.au",
url:"http://www.abc.net.au",
surl:"http://search.abc.net.au/search/search.cgi?sort=&collection=abcall&query=",
desc:"Main public broadcaster"},

{id:"au_newsau",
type:"news",
cc:"au",
name:"newsau",
label:"news.com.au",
url:"http://searchresults.news.com.au",
surl:"http://searchresults.news.com.au/servlet/Search?site=ninews&queryterm=",
desc:""},

{id:"at_yahoo",
type:"portals",
cc:"at",
name:"yahoo",
label:"yahoo.at",
url:"http://www.yahoo.at",
surl:"http://at.search.yahoo.com/search?p=",
desc:""},

{id:"at_amazon",
type:"shopping",
cc:"at",
name:"amazon",
label:"amazon.at",
url:"http://www.amazon.de/gp/redirect.html?ie=UTF8&location=http%3A%2F%2Famazon.at%2F&site-redirect=at&tag=wwwmadmaxmatd-21&linkCode=ur2&camp=1638&creative=6742",
surl:"http://www.amazon.de/gp/search?tag=wwwmadmaxmatd-21&index=blended&location=http%3A%2F%2Famazon.at%2F&site-redirect=at&linkCode=ur2&camp=1638&creative=6742&keywords=",
desc:""},

{id:"at_ebay",
type:"shopping",
cc:"at",
name:"ebay",
label:"ebay.at",
url:"http://ebay.at",
surl:"http://search.ebay.at/",
desc:""},

{id:"at_otto",
type:"shopping",
cc:"at",
name:"otto",
label:"ottoversand.at",
url:"http://partners.webmasterplan.com/click.asp?ref=436362&site=3433&type=b33&bnb=33",
surl:"http://partners.webmasterplan.com/click.asp?ref=436362&site=3433&type=b33&bnb=33&",
desc:""},

{id:"at_geizhals",
type:"shopping",
cc:"at",
name:"geizhals",
label:"geizhals.at",
url:"http://geizhals.at",
surl:"http://geizhals.at/?fs=",
desc:""},

{id:"ca_yahoo",
type:"portals",
cc:"ca",
name:"yahoo",
label:"yahoo.ca",
url:"http://www.yahoo.ca",
surl:"http://ca.search.yahoo.com/search?p=",
desc:""},

{id:"ca_ebay",
type:"shopping",
cc:"ca",
name:"ebay",
label:"ebay.ca",
url:"http://www.ebay.ca",
surl:"http://search.ebay.ca/",
desc:""},

{id:"ca_amazon",
type:"shopping",
cc:"ca",
name:"amazon",
label:"amazon.ca",
url:"http://www.amazon.ca/gp/redirect.html?ie=UTF8&location=http%3A%2F%2Fwww.amazon.ca%2F&tag=mysearches05-20&linkCode=ur2&camp=15121&creative=330641",
surl:"http://www.amazon.ca/gp/search?ie=UTF8&tag=mysearches05-20&index=blended&linkCode=ur2&camp=15121&creative=330641&keywords=",
desc:""},

{id:"ch_yahoo",
type:"portals",
cc:"ch",
name:"yahoo",
label:"yahoo.ch",
url:"http://www.yahoo.ch",
surl:"http://ch.search.yahoo.com/search?p=",
desc:""},

{id:"ch_searchch",
type:"portals",
cc:"ch",
name:"searchch",
label:"search.ch",
url:"http://www.search.ch",
surl:"http://www.search.ch/search.html?loc=ch&q=",
desc:"The Swiss Search Engine"},

{id:"ch_ebay",
type:"shopping",
cc:"ch",
name:"ebay",
label:"ebay.ch",
url:"http://ebay.ch",
surl:"http://search.ebay.ch/",
desc:""},

{id:"ch_toppreise",
type:"shopping",
cc:"ch",
name:"toppreise",
label:"toppreise.ch",
url:"http://www.toppreise.ch",
surl:"http://www.toppreise.ch/index.php?search=",
desc:"Preissuchmaschine Toppreise.ch"},

{id:"ch_ricardo",
type:"shopping",
cc:"ch",
name:"ricardo",
label:"ricardo.ch",
url:"http://www.ricardo.ch",
surl:"http://my.ricardo.ch/search/search.asp?txtSearch=",
desc:""},

{id:"ch_1advd",
type:"shopping",
cc:"ch",
name:"1advd",
label:"1a-dvdshop.ch",
url:"http://www.1a-dvdshop.ch",
surl:"http://www.1a-dvdshop.ch/DefaultTOP.asp?sb=",
desc:"1a-dvd Shop"},

{id:"cn_baidu",
type:"portals",
cc:"cn",
name:"baidu",
label:"baidu.com",
url:"http://www.baidu.com",
surl:"http://www.baidu.com/s?wd=",
desc:""},

{id:"de_yahoo",
type:"portals",
cc:"de",
name:"yahoo",
label:"yahoo.de",
url:"http://www.yahoo.de",
surl:"http://de.search.yahoo.com/search?p=",
desc:""},

{id:"de_lycos",
type:"portals",
cc:"de",
name:"lycos",
label:"lycos.de",
url:"http://www.lycos.de",
surl:"http://suche.lycos.de/cgi-bin/pursuit?query=",
desc:""},

{id:"de_web",
type:"portals",
cc:"de",
name:"web",
label:"web.de",
url:"http://www.web.de",
surl:"http://suche.web.de/search/web/?allparams=&smode=&webRb=int&su=",
desc:""},

{id:"de_dmoz",
type:"portals",
cc:"de",
name:"dmoz",
label:"dmoz.de",
url:"http://www.dmoz.de",
surl:"http://search.dmoz.org/cgi-bin/search?all=no&cat=World%2FDeutsch&search=",
desc:""},

{id:"de_ebay",
type:"shopping",
cc:"de",
name:"ebay",
label:"ebay.de",
url:"http://ebay.de",
surl:"http://search.ebay.de/",
desc:""},

{id:"de_amazon",
type:"shopping",
cc:"de",
name:"amazon",
label:"amazon.de",
url:"http://www.amazon.de/gp/redirect.html?ie=UTF8&location=http%3A%2F%2Fwww.amazon.de%2F&site-redirect=de&tag=wwwmadmaxmatd-21&linkCode=ur2&camp=1638&creative=6742",
surl:"http://www.amazon.de/gp/search?tag=wwwmadmaxmatd-21&index=blended&linkCode=ur2&camp=1638&creative=6742&keywords=",
desc:""},

{id:"de_otto",
type:"shopping",
cc:"de",
name:"otto",
label:"otto.de",
url:"http://partners.webmasterplan.com/click.asp?ref=436362&site=2950&type=b29&bnb=29",
surl:"http://partners.webmasterplan.com/click.asp?ref=436362&site=2950&type=text&tnb=17&prd=yes&affdeep=",
desc:""},

{id:"de_guenstiger",
type:"shopping",
cc:"de",
name:"guenstiger",
label:"guenstiger.de",
url:"http://www3.guenstiger.de/gt/main.asp",
surl:"http://www3.guenstiger.de/gt/main.asp?suche=",
desc:"Preis-Suchmaschine"},

{id:"de_billiger",
type:"shopping",
cc:"de",
name:"billiger",
label:"billiger.de",
url:"http://www.billiger.de",
surl:"http://www.billiger.de/suche.html?go=Suchen&userkatsuggest=&houston=1&searchstring=",
desc:""},

{id:"de_geizhals",
type:"shopping",
cc:"de",
name:"geizhals",
label:"geizhals.at",
url:"http://geizhals.at/deutschland",
surl:"http://geizhals.at/deutschland/?fs=",
desc:""},

{id:"de_preistrend",
type:"shopping",
cc:"de",
name:"preistrend",
label:"preistrend.de",
url:"http://www.preistrend.de",
surl:"http://preistrend.de/suchen.php?q=",
desc:""},

{id:"de_evendi",
type:"shopping",
cc:"de",
name:"evendi",
label:"evendi.de",
url:"http://www.evendi.de",
surl:"http://www.evendi.de/jsp/eVendi2004/search.jsp?name=",
desc:""},

{id:"de_doorone",
type:"shopping",
cc:"de",
name:"doorone",
label:"doorone.de",
url:"http://www.doorone.de",
surl:"http://www.doorone.de/xFS?KW=",
desc:""},

{id:"de_testberichte",
type:"shopping",
cc:"de",
name:"testberichte",
label:"testberichte.de",
url:"http://www.testberichte.de",
surl:"http://www.testberichte.de/d/search.php?searchstr=",
desc:""},

{id:"de_yatego",
type:"shopping",
cc:"de",
name:"yatego",
label:"yatego.com",
url:"http://www.yatego.com",
surl:"http://www.yatego.com/index.htm?cl=mallsearch&query=",
desc:""},

{id:"de_hardwareschotte",
type:"shopping",
cc:"de",
name:"hardwareschotte",
label:"hardwareschotte.de",
url:"http://www.hardwareschotte.de",
surl:"http://www.hardwareschotte.de/preise.php3?seachrange=all&searchstring=",
desc:""},

{id:"de_misterwong",
type:"bookmarking",
cc:"de",
name:"misterwong",
label:"mister-wong.de",
url:"http://www.mister-wong.de",
surl:"http://www.mister-wong.de/search/?search_type=w&btn=suchen&keywords=",
desc:""},

{id:"de_wikipedia",
type:"knowledge",
cc:"de",
name:"wikipedia",
label:"de.wikipedia",
url:"http://de.wikipedia.org",
surl:"http://de.wikipedia.org/wiki/Spezial:Search?go=Artikel&search=",
desc:""},

{id:"de_dejure",
type:"knowledge",
cc:"de",
name:"dejure",
label:"dejure.org",
url:"http://dejure.org",
surl:"http://dejure.org/cgi-bin/suche?Suchenach=",
desc:""},

{id:"de_leocn",
type:"knowledge",
cc:"de",
name:"leocn",
label:"leo.org CN",
url:"http://dict.leo.org/chde",
surl:"http://dict.leo.org/chde?search=",
desc:""},

{id:"de_leoen",
type:"knowledge",
cc:"de",
name:"leoen",
label:"leo.org EN",
url:"http://dict.leo.org/ende",
surl:"http://dict.leo.org/ende?search=",
desc:""},

{id:"de_leoes",
type:"knowledge",
cc:"de",
name:"leoes",
label:"leo.org ES",
url:"http://dict.leo.org/esde",
surl:"http://dict.leo.org/esde?search=",
desc:""},

{id:"de_leofr",
type:"knowledge",
cc:"de",
name:"leofr",
label:"leo.org FR",
url:"http://dict.leo.org/frde",
surl:"http://dict.leo.org/frde?search=",
desc:""},

{id:"de_leoit",
type:"knowledge",
cc:"de",
name:"leoit",
label:"leo.org IT",
url:"http://dict.leo.org/itde",
surl:"http://dict.leo.org/itde?search=",
desc:""},

{id:"de_beolingusen",
type:"knowledge",
cc:"de",
name:"beolingusen",
label:"dict.tu-chemnitz.de EN",
url:"http://dict.tu-chemnitz.de/dings.cgi?lang=de;service=deen",
surl:"http://dict.tu-chemnitz.de/dings.cgi?lang=de&service=deen&query=",
desc:"",
icon:"beolingus"},

{id:"de_beolinguses",
type:"knowledge",
cc:"de",
name:"beolinguses",
label:"dict.tu-chemnitz.de ES",
url:"http://dict.tu-chemnitz.de/dings.cgi?lang=de;service=dees",
surl:"http://dict.tu-chemnitz.de/dings.cgi?lang=de&service=dees&query=",
desc:"",
icon:"beolingus"},

{id:"de_beolinguspt",
type:"knowledge",
cc:"de",
name:"beolinguspt",
label:"dict.tu-chemnitz.de PT",
url:"http://dict.tu-chemnitz.de/dings.cgi?lang=de;service=dept",
surl:"http://dict.tu-chemnitz.de/dings.cgi?lang=de&service=dept&query=",
desc:"",
icon:"beolingus"},

{id:"de_babdecn",
type:"knowledge",
cc:"de",
name:"babdecn",
label:"bab.la DE-CN",
url:"http://bab.la/woerterbuch/deutsch-chinesisch",
surl:"http://bab.la/woerterbuch/deutsch-chinesisch/",
desc:"",
icon:"babla"},

{id:"de_babdeen",
type:"knowledge",
cc:"de",
name:"babdeen",
label:"bab.la DE-EN",
url:"http://bab.la/woerterbuch/deutsch-englisch",
surl:"http://bab.la/woerterbuch/deutsch-englisch/",
desc:"",
icon:"babla"},

{id:"de_babdees",
type:"knowledge",
cc:"de",
name:"babdees",
label:"bab.la DE-ES",
url:"http://bab.la/woerterbuch/deutsch-spanisch",
surl:"http://bab.la/woerterbuch/deutsch-spanisch/",
desc:"",
icon:"babla"},

{id:"de_babdefr",
type:"knowledge",
cc:"de",
name:"babdefr",
label:"bab.la DE-FR",
url:"http://bab.la/woerterbuch/deutsch-franzoesisch",
surl:"http://bab.la/woerterbuch/deutsch-franzoesisch/",
desc:"",
icon:"babla"},

{id:"de_babdepl",
type:"knowledge",
cc:"de",
name:"babdepl",
label:"bab.la DE-PL",
url:"http://bab.la/woerterbuch/deutsch-polnisch",
surl:"http://bab.la/woerterbuch/deutsch-polnisch/",
desc:"",
icon:"babla"},

{id:"de_babdept",
type:"knowledge",
cc:"de",
name:"babdept",
label:"bab.la DE-PT",
url:"http://bab.la/woerterbuch/deutsch-portugiesisch",
surl:"http://bab.la/woerterbuch/deutsch-portugiesisch/",
desc:"",
icon:"babla"},

{id:"de_babderu",
type:"knowledge",
cc:"de",
name:"babderu",
label:"bab.la DE-RU",
url:"http://bab.la/woerterbuch/deutsch-russisch",
surl:"http://bab.la/woerterbuch/deutsch-russisch/",
desc:"",
icon:"babla"},

{id:"de_babdetr",
type:"knowledge",
cc:"de",
name:"babdetr",
label:"bab.la DE-TR",
url:"http://bab.la/woerterbuch/deutsch-tuerkisch",
surl:"http://bab.la/woerterbuch/deutsch-tuerkisch/",
desc:"",
icon:"babla"},

{id:"de_uitmuntend",
type:"knowledge",
cc:"de",
name:"uitmuntend",
label:"uitmuntend.de DE-NL",
url:"http://www.uitmuntend.de",
surl:"http://www.uitmuntend.de/search.html?search=",
desc:""},

{id:"de_woerterbuch",
type:"knowledge",
cc:"de",
name:"woerterbuch",
label:"woerterbuch.info",
url:"http://www.woerterbuch.info",
surl:"http://www.woerterbuch.info/?s=thesaurus&query=",
desc:""},

{id:"de_duden",
type:"knowledge",
cc:"de",
name:"duden",
label:"duden.de",
url:"http://www.duden-suche.de/",
surl:"http://www.duden-suche.de/suche/trefferliste.php?suchbegriff[AND]=",
desc:""},

{id:"de_canoo",
type:"knowledge",
cc:"de",
name:"canoo",
label:"canoo.net",
url:"http://www.canoo.net",
surl:"http://www.canoo.net/services/Controller?MenuId=Search&service=canooNet<=de&input=",
desc:""},

{id:"de_dict",
type:"knowledge",
cc:"de",
name:"dict",
label:"dict.cc",
url:"http://www.dict.cc",
surl:"http://www.dict.cc/?s=",
desc:""},

{id:"de_abkuerzungen",
type:"knowledge",
cc:"de",
name:"abkuerzungen",
label:"abkuerzungen.de",
url:"http://www.abkuerzungen.de",
surl:"http://www.abkuerzungen.de/pc/html/result.php?language=DE&x=21&y=8&abbreviation=",
desc:""},

{id:"de_werweisswas",
type:"knowledge",
cc:"de",
name:"werweisswas",
label:"wer-weiss-was.de",
url:"http://www.wer-weiss-was.de",
surl:"http://www.wer-weiss-was.de/app/search/global?search_what=e&search_what=t&submit.search=1&bool=a&type=beginnings&searchtext=",
desc:""},

{id:"de_dnb",
type:"knowledge",
cc:"de",
name:"dnb",
label:"Dt. Nationalbibliothek",
url:"http://www.d-nb.de",
surl:"https://portal.d-nb.de/opac.htm?method=simpleSearch&query=",
desc:"Website der deutschen Nationalbibliothek"},

{id:"de_studivz",
type:"community",
cc:"de",
name:"studivz",
label:"studiVZ.net",
url:"http://www.studivz.net",
surl:"http://www.studivz.net/search.php?do_search=1&name=",
desc:""},

{id:"de_meinvz",
type:"community",
cc:"de",
name:"meinvz",
label:"meinVZ.net",
url:"http://www.meinvz.net",
surl:"http://www.meinvz.net/search.php?do_search=1&name=",
desc:""},

{id:"de_xing",
type:"community",
cc:"de",
name:"xing",
label:"xing.com",
url:"http://www.xing.com",
surl:"https://www.xing.com/app/search?op=universal&universal=",
desc:""},

{id:"de_lastfm",
type:"community",
cc:"de",
name:"lastfm",
label:"lastfm.de",
url:"http://www.lastfm.de",
surl:"http://www.lastfm.de/music/?q=",
desc:""},

{id:"de_stayfriends",
type:"community",
cc:"de",
name:"stayfriends",
label:"stayfriends.de",
url:"http://www.stayfriends.de",
surl:"http://www.stayfriends.de/j/ViewController?submitaction=suchen&action=personSearch&q=",
desc:"Schulfreunde wiederfinden"},

{id:"de_spiegel",
type:"news",
cc:"de",
name:"spiegel",
label:"spiegel.de",
url:"http://www.spiegel.de",
surl:"http://service.spiegel.de/digas/servlet/find?S=",
desc:""},

{id:"de_yigg",
type:"news",
cc:"de",
name:"yigg",
label:"yigg.de",
url:"http://www.yigg.de",
surl:"http://www.yigg.de/suche?domains=www.yigg.de&sa=Google-Suche&sitesearch=www.yigg.de&client=pub-1406192967534280&forid=1&channel=8430379320&ie=ISO-8859-1&oe=ISO-8859-1&cof=GALT%3A%23008000%3BGL%3A1%3BDIV%3A%23336699%3BVLC%3A663399%3BAH%3Acenter%3BBGC%3AFFFFFF%3BLBGC%3A336699%3BALC%3A0000FF%3BLC%3A0000FF%3BT%3A000000%3BGFNT%3A0000FF%3BGIMP%3A0000FF%3BFORID%3A11&hl=de&q=",
desc:""},

{id:"de_ftd",
type:"finance",
cc:"de",
name:"ftd",
label:"ftd.de",
url:"http://ftd.de",
surl:"http://ftd.de/recherche/suche.html?suchtyp=news&q=",
desc:""},

{id:"de_finanznachrichten",
type:"finance",
cc:"de",
name:"finanznachrichten",
label:"finanznachrichten.de",
url:"http://www.finanznachrichten.de",
surl:"http://www.finanznachrichten.de/suche/suchergebnis.asp?words=",
desc:""},

{id:"de_onvista",
type:"finance",
cc:"de",
name:"onvista",
label:"onvista.de",
url:"http://www.onvista.de",
surl:"http://www.onvista.de/suche.html?SEARCH_VALUE=",
desc:""},

{id:"de_finanzen",
type:"finance",
cc:"de",
name:"finanzen",
label:"finanzen.net",
url:"http://www.finanzen.net",
surl:"http://www.finanzen.net/suchergebnis.asp?frmAktiensucheTextfeld=",
desc:""},

{id:"de_fimatex",
type:"finance",
cc:"de",
name:"fimatex",
label:"fimatex.de",
url:"http://partners.webmasterplan.com/click.asp?ref=436362&site=4077&type=text&tnb=1",
surl:"http://www.fimatex.de/resultat_recherche_code.phtml?code=",
desc:""},

{id:"de_dkb",
type:"finance",
cc:"de",
name:"dkb",
label:"dkb.de",
url:"http://www.dkb.de",
surl:"http://www.dkb.de/cgi-bin/kurse.pl?search=",
desc:"Kursabfrage"},

{id:"de_wettercom",
type:"diverse",
cc:"de",
name:"wettercom",
label:"wetter.com",
url:"http://www.wetter.com",
surl:"http://www.wetter.com/v2/?SID=&LANG=DE&LOC=7004&LOCFULL=7000&button1=suchen+++&search=",
desc:""},

{id:"de_wetterde",
type:"diverse",
cc:"de",
name:"wetterde",
label:"wetter.de",
url:"http://www.wetter.de",
surl:"http://wetter.rtl.de/deutschland/uebersicht.php?ort=",
desc:""},

{id:"de_gelbeseiten",
type:"diverse",
cc:"de",
name:"gelbeseiten",
label:"gelbeseiten.de",
url:"http://www.gelbeseiten.de",
surl:"http://www.gelbeseiten.de/yp/search.yp?subject=",
desc:""},

{id:"de_telefonbuch",
type:"diverse",
cc:"de",
name:"telefonbuch",
label:"telefonbuch.de",
url:"http://www.telefonbuch.de",
surl:"http://www.telefonbuch.de/?kw=",
desc:""},

{id:"de_oertliche",
type:"diverse",
cc:"de",
name:"oertliche",
label:"oertliche.de",
url:"http://www.dasoertliche.de",
surl:"http://www.dasoertliche.de/?kw=",
desc:""},

{id:"de_bahn",
type:"diverse",
cc:"de",
name:"bahn",
label:"bahn.de",
url:"http://www.bahn.de",
surl:"http://www.bahn.de/bin/iquery?db=p&text=",
desc:""},

{id:"de_ancestry",
type:"diverse",
cc:"de",
name:"ancestry",
label:"ancestry.de",
url:"http://partners.webmasterplan.com/click.asp?ref=436362&site=4263&type=text&tnb=1",
surl:"http://www.ancestry.de/learn/learningcenters/namedist.aspx?name=",
desc:"the from where your family is coming"},

{id:"de_chefkoch",
type:"diverse",
cc:"de",
name:"chefkoch",
label:"chefkoch.de",
url:"http://www.chefkoch.de",
surl:"http://www.chefkoch.de/suche.php?from_form=1&suche=",
desc:""},

{id:"de_mytv",
type:"media",
cc:"de",
name:"mytv",
label:"mytv.de",
url:"http://www.mytv.de",
surl:"http://www.mytv.de/search.html?q=",
desc:""},

{id:"de_myvideo",
type:"media",
cc:"de",
name:"myvideo",
label:"myvideo.de",
url:"http://www.myvideo.de",
surl:"http://www.myvideo.de/online/page.php?P=117&volltext=",
desc:""},

{id:"de_ofdb",
type:"media",
cc:"de",
name:"ofdb",
label:"ofdb.de",
url:"http://www.ofdb.de",
surl:"http://www.ofdb.de/view.php?page=suchergebnis&SText=",
desc:""},

{id:"de_filmstarts",
type:"media",
cc:"de",
name:"filmstarts",
label:"filmstarts.de",
url:"http://www.filmstarts.de",
surl:"http://www.google.com/custom?hl=de&oe=ISO-8859-1&client=pub-7697668210662178&cof=FORID:1%3BL:http://bilder.filmstarts.de/design/filmstarts/topbanner_google.jpg%3BLH:50%3BLW:660%3BGL:1%3BBGC:FFFFFF%3BT:%23000066%3BLC:%230a2155%3BVLC:%23000033%3BALC:%230a2155%3BGALT:%230A2155%3BGFNT:%23194198%3BGIMP:%23194198%3BDIV:%230a2155%3BLBGC:194198%3BAH:left%3BS:http://www.filmstarts.de%3B&domains=www.filmstarts.de&sitesearch=www.filmstarts.de&sa=X&oi=spell&resnum=0&ct=result&cd=1&spell=1&q=",
desc:""},

{id:"de_filmspiegel",
type:"media",
cc:"de",
name:"filmspiegel",
label:"filmspiegel.de",
url:"http://www.filmspiegel.de",
surl:"http://www.filmspiegel.de/suche/index.php?begriff=",
desc:""},

{id:"de_kino",
type:"media",
cc:"de",
name:"kino",
label:"kino.de",
url:"http://www.kino.de",
surl:"http://www.kino.de/search.php?mode=megaSearch&searchCategory=all&inputSearch=",
desc:""},

{id:"de_selfhtml",
type:"programming",
cc:"de",
name:"selfhtml",
label:"selfhtml.org",
url:"http://de.selfhtml.org",
surl:"http://de.selfhtml.org/navigation/suche/index.htm?Suchanfrage=",
desc:""},

{id:"dk_yahoo",
type:"portals",
cc:"dk",
name:"yahoo",
label:"yahoo.dk",
url:"http://www.yahoo.dk",
surl:"http://dk.search.yahoo.com/search?p=",
desc:""},

{id:"dk_jubii",
type:"portals",
cc:"dk",
name:"jubii",
label:"jubii.dk",
url:"http://www.jubii.dk",
surl:"http://search.jubii.dk/cgi-bin/pursuit?cat=loc&query=",
desc:""},

{id:"dk_eniro",
type:"portals",
cc:"dk",
name:"eniro",
label:"eniro.dk",
url:"http://www.eniro.dk",
surl:"http://www.eniro.dk/query?what=web_local&search_word=",
desc:""},

{id:"dk_wikipedia",
type:"knowledge",
cc:"dk",
name:"wikipedia",
label:"da.wikipedia",
url:"http://da.wikipedia.org",
surl:"http://da.wikipedia.org/wiki/Speciel:Search?go=G%C3%A5+til&search=",
desc:""},

{id:"dk_krak",
type:"diverse",
cc:"dk",
name:"krak",
label:"krak.dk",
url:"http://www.krak.dk",
surl:"http://www.krak.dk/Firma/Resultat.aspx?Query=",
desc:""},

{id:"es_yahoo",
type:"portals",
cc:"es",
name:"yahoo",
label:"yahoo.es",
url:"http://www.yahoo.es",
surl:"http://es.search.yahoo.com/search?p=",
desc:""},

{id:"es_ebay",
type:"shopping",
cc:"es",
name:"ebay",
label:"ebay.es",
url:"http://www.ebay.es",
surl:"http://search.ebay.es/",
desc:""},

{id:"es_wikipedia",
type:"knowledge",
cc:"es",
name:"wikipedia",
label:"es.wikipedia",
url:"http://es.wikipedia.org",
surl:"http://es.wikipedia.org/wiki/Especial:Search?go=Ir&search=",
desc:""},

{id:"fr_yahoo",
type:"portals",
cc:"fr",
name:"yahoo",
label:"yahoo.fr",
url:"http://www.yahoo.fr",
surl:"http://fr.search.yahoo.com/search?p=",
desc:""},

{id:"fr_dmoz",
type:"portals",
cc:"fr",
name:"dmoz",
label:"dmoz.fr",
url:"http://www.dmoz.fr",
surl:"http://dmoz.fr/default.asp?search=",
desc:""},

{id:"fr_amazon",
type:"shopping",
cc:"fr",
name:"amazon",
label:"amazon.fr",
url:"http://www.amazon.fr/gp/redirect.html?ie=UTF8&location=http%3A%2F%2Fwww.amazon.fr%2F&tag=mysearches-21&linkCode=ur2&camp=1642&creative=6746",
surl:"http://www.amazon.fr/gp/search?ie=UTF8&tag=mysearches-21&index=blended&linkCode=ur2&camp=1642&creative=6746&keywords=",
desc:""},

{id:"fr_ebay",
type:"shopping",
cc:"fr",
name:"ebay",
label:"ebay.fr",
url:"http://www.ebay.fr",
surl:"http://search.ebay.fr/",
desc:""},

{id:"fr_doorone",
type:"shopping",
cc:"fr",
name:"doorone",
label:"doorone.fr",
url:"http://www.doorone.fr",
surl:"http://doorone.fr/xFS?KW=",
desc:""},

{id:"fr_wikipedia",
type:"knowledge",
cc:"fr",
name:"wikipedia",
label:"fr.wikipedia",
url:"http://fr.wikipedia.org",
surl:"http://fr.wikipedia.org/wiki/Especial:Search?go=Ir&search=",
desc:""},

{id:"it_yahoo",
type:"portals",
cc:"it",
name:"yahoo",
label:"yahoo.it",
url:"http://www.yahoo.it",
surl:"http://it.search.yahoo.com/search?p=",
desc:""},

{id:"it_ebay",
type:"shopping",
cc:"it",
name:"ebay",
label:"ebay.it",
url:"http://www.ebay.it",
surl:"http://search.ebay.it/",
desc:""},

{id:"it_wikipedia",
type:"knowledge",
cc:"it",
name:"wikipedia",
label:"it.wikipedia",
url:"http://it.wikipedia.org",
surl:"http://it.wikipedia.org/wiki/Speciale:Search?go=Vai&search=",
desc:""},

{id:"jp_yahoo",
type:"portals",
cc:"jp",
name:"yahoo",
label:"yahoo.co.jp",
url:"http://www.yahoo.co.jp",
surl:"http://search.yahoo.co.jp/search?p=",
desc:""},

{id:"jp_greengoo",
type:"portals",
cc:"jp",
name:"greengoo",
label:"green.goo.ne.jp",
url:"http://green.goo.ne.jp",
surl:"http://green.search.goo.ne.jp/search?OE=UTF-8&IE=UTF-8&from=eco_search&MT=",
desc:""},

{id:"jp_amazon",
type:"shopping",
cc:"jp",
name:"amazon",
label:"amazon.co.jp",
url:"http://www.amazon.co.jp",
surl:"http://www.amazon.co.jp/exec/obidos/redirect?link_code=ur2&tag=wwwmadmaxmatd-21&camp=1638&creative=6742&path=external-search%3Fsearch-type=ss%26index=blended%26keyword=",
desc:""},

{id:"jp_wikipedia",
type:"knowledge",
cc:"jp",
name:"wikipedia",
label:"ja.wikipedia",
url:"http://ja.wikipedia.org",
surl:"http://ja.wikipedia.org/wiki/%E7%89%B9%E5%88%A5:Search?search=",
desc:""},

{id:"jp_gnavi",
type:"diverse",
cc:"jp",
name:"gnavi",
label:"gnavi.co.jp",
url:"http://www.gnavi.co.jp",
surl:"http://gsearch.gnavi.co.jp/rest/search.php?key=",
desc:"restraunt search"},

{id:"jp_ruby",
type:"programming",
cc:"jp",
name:"ruby",
label:"ruby-lang.org/ja",
url:"http://www.ruby-lang.org/ja",
surl:"http://www.ruby-lang.org/ja/search/?q=",
desc:"ruby official in japanese"},

{id:"nl_yahoo",
type:"portals",
cc:"nl",
name:"yahoo",
label:"yahoo.nl",
url:"http://www.yahoo.nl",
surl:"http://nl.search.yahoo.com/search?p=",
desc:""},

{id:"nl_vinden",
type:"portals",
cc:"nl",
name:"vinden",
label:"vinden.nl",
url:"http://www.vinden.nl",
surl:"http://www.vinden.nl/?q=",
desc:""},

{id:"nl_dmoz",
type:"portals",
cc:"nl",
name:"dmoz",
label:"dmoz.nl",
url:"http://www.dmoz.nl",
surl:"http://search.dmoz.org/cgi-bin/search?cat=World%2FNederlands&all=no&search=",
desc:""},

{id:"nl_ebay",
type:"shopping",
cc:"nl",
name:"ebay",
label:"ebay.nl",
url:"http://www.ebay.nl",
surl:"http://search.ebay.nl/",
desc:""},

{id:"nl_wikipedia",
type:"knowledge",
cc:"nl",
name:"wikipedia",
label:"nl.wikipedia",
url:"http://nl.wikipedia.org",
surl:"http://nl.wikipedia.org/wiki/Speciaal:Search?go=Artikel&search=",
desc:""},

{id:"nl_uitmuntend",
type:"knowledge",
cc:"nl",
name:"uitmuntend",
label:"uitmuntend.de DE-NL",
url:"http://www.uitmuntend.de",
surl:"http://www.uitmuntend.de/search.html?search=",
desc:""},

{id:"se_yahoo",
type:"portals",
cc:"se",
name:"yahoo",
label:"yahoo.se",
url:"http://se.yahoo.com/",
surl:"http://se.search.yahoo.com/search?p=",
desc:""},

{id:"se_spray",
type:"portals",
cc:"se",
name:"spray",
label:"spray.se",
url:"http://www.spray.se",
surl:"http://lycossvar.spray.se/cgi-bin/pursuit?query=",
desc:""},

{id:"se_eniro",
type:"portals",
cc:"se",
name:"eniro",
label:"eniro.se",
url:"http://www.eniro.se",
surl:"http://www.eniro.se/query?what=se&q=",
desc:""},

{id:"se_ebay",
type:"shopping",
cc:"se",
name:"ebay",
label:"ebay.se",
url:"http://www.ebay.se",
surl:"http://www.ebay.se/listResults?browse=0&Query=",
desc:""},

{id:"se_wikipedia",
type:"knowledge",
cc:"se",
name:"wikipedia",
label:"sv.wikipedia",
url:"http://sv.wikipedia.org",
surl:"http://sv.wikipedia.org/wiki/Special:Search?go=G%C3%A5+till&search=",
desc:""},

{id:"se_hitta",
type:"diverse",
cc:"se",
name:"hitta",
label:"hitta.se",
url:"http://www.hitta.se",
surl:"http://www.hitta.se/SearchMixed.aspx?UCSB%3aTextBoxWho=",
desc:""},

{id:"uk_yahoo",
type:"portals",
cc:"uk",
name:"yahoo",
label:"yahoo.co.uk",
url:"http://www.yahoo.co.uk",
surl:"http://uk.search.yahoo.com/search?p=",
desc:""},

{id:"uk_bbc",
type:"news",
cc:"uk",
name:"bbc",
label:"bbc.co.uk",
url:"http://www.bbc.co.uk",
surl:"http://search.bbc.co.uk/cgi-bin/search/results.pl?q=",
desc:""},

{id:"uk_guardian",
type:"news",
cc:"uk",
name:"guardian",
label:"guardian.co.uk",
url:"http://www.guardian.co.uk",
surl:"http://browse.guardian.co.uk/search?search=",
desc:""},

{id:"uk_newscientist",
type:"news",
cc:"uk",
name:"newscientist",
label:"newscientist.com",
url:"http://www.newscientist.com",
surl:"http://www.newscientist.com/search.ns?query=",
desc:""},

{id:"uk_ebay",
type:"shopping",
cc:"uk",
name:"ebay",
label:"ebay.co.uk",
url:"http://www.ebay.co.uk",
surl:"http://search.ebay.co.uk/",
desc:""},

{id:"uk_amazon",
type:"shopping",
cc:"uk",
name:"amazon",
label:"amazon.co.uk",
url:"http://www.amazon.co.uk/gp/redirect.html?ie=UTF8&location=http%3A%2F%2Fwww.amazon.co.uk%2F&tag=mulseagad05-21&linkCode=ur2&camp=1634&creative=6738",
surl:"http://www.amazon.co.uk/gp/search?ie=UTF8&tag=mulseagad05-21&index=blended&linkCode=ur2&camp=1634&creative=6738&keywords=",
desc:""},

{id:"uk_doorone",
type:"shopping",
cc:"uk",
name:"doorone",
label:"doorone.uk",
url:"http://www.doorone.co.uk",
surl:"http://doorone.co.uk/xFS?KW=",
desc:""},

{id:"uk_play",
type:"shopping",
cc:"uk",
name:"play",
label:"play.com",
url:"http://www.play.com",
surl:"http://www.play.com/Search.aspx?searchtype=allproducts&searchstring=",
desc:""},

{id:"us_yahoo",
type:"portals",
cc:"us",
name:"yahoo",
label:"yahoo.com",
url:"http://www.yahoo.com",
surl:"http://search.yahoo.com/search?p=",
desc:""},

{id:"us_creativecommons",
type:"portals",
cc:"us",
name:"creativecommons",
label:"creativecommons.org",
url:"http://creativecommons.org",
surl:"http://search.creativecommons.org/?q=",
desc:""},

{id:"us_metacrawler",
type:"portals",
cc:"us",
name:"metacrawler",
label:"metacrawler.com",
url:"http://www.metacrawler.com",
surl:"http://www.metacrawler.com/info.metac/search/web/",
desc:""},

{id:"us_ebay",
type:"shopping",
cc:"us",
name:"ebay",
label:"ebay.com",
url:"http://www.ebay.com",
surl:"http://search.ebay.com/",
desc:""},

{id:"us_amazon",
type:"shopping",
cc:"us",
name:"amazon",
label:"amazon.com",
url:"http://www.amazon.com/gp/redirect.html?ie=UTF8&location=http%3A%2F%2Fwww.amazon.com%2F&tag=mysearches-20&linkCode=ur2&camp=1789&creative=9325",
surl:"http://www.amazon.com/gp/search?ie=UTF8&tag=mysearches-20&index=blended&linkCode=ur2&camp=1789&creative=9325&keywords=",
desc:""},

{id:"us_ft",
type:"finance",
cc:"us",
name:"ft",
label:"financialtimes.com",
url:"http://www.ft.com",
surl:"http://search.ft.com/searchResults?queryText=",
desc:""},

{id:"us_wikipedia",
type:"knowledge",
cc:"us",
name:"wikipedia",
label:"en.wikipedia",
url:"http://en.wikipedia.org",
surl:"http://en.wikipedia.org/wiki/Spezial:Search?go=Artikel&search=",
desc:""},

{id:"us_about",
type:"knowledge",
cc:"us",
name:"about",
label:"about.com",
url:"http://www.about.com",
surl:"http://search.about.com/fullsearch.htm?terms=",
desc:""},

{id:"us_hakia",
type:"knowledge",
cc:"us",
name:"hakia",
label:"hakia.com",
url:"http://www.hakia.com",
surl:"http://www.hakia.com/search.aspx?q=",
desc:""},

{id:"us_answer",
type:"knowledge",
cc:"us",
name:"answer",
label:"answer.com",
url:"http://www.answer.com",
surl:"http://www.answers.com/main/ntquery?s=",
desc:"The worlds greatest encyclodictionalmanacapedia"},

{id:"us_thefreedictionary",
type:"knowledge",
cc:"us",
name:"thefreedictionary",
label:"thefreedictionary.com",
url:"http://www.thefreedictionary.com",
surl:"http://www.thefreedictionary.com/",
desc:""},

{id:"us_wikihow",
type:"knowledge",
cc:"us",
name:"wikihow",
label:"wikihow.com",
url:"http://www.wikihow.com",
surl:"http://www.wikihow.com/Special:LSearch?fulltext=Search&search=",
desc:""},

{id:"us_acronymfinder",
type:"knowledge",
cc:"us",
name:"acronymfinder",
label:"acronymfinder.com",
url:"http://www.acronymfinder.com",
surl:"http://www.acronymfinder.com/af-query.asp?Acronym=",
desc:""},

{id:"us_urbandictionary",
type:"knowledge",
cc:"us",
name:"urbandictionary",
label:"urbandictionary.com",
url:"http://www.urbandictionary.com",
surl:"http://www.urbandictionary.com/define.php?term=",
desc:""},

{id:"aa_google",
type:"google",
cc:"",
name:"google",
label:"google.com (ENTER)",
url:"http://google.com",
surl:"http://www.google.com/search?q=",
desc:"Also search google with ENTER"},

{id:"aa_googleblogsearch",
type:"google",
cc:"",
name:"googleblogsearch",
label:"blogsearch.google.com",
url:"http://blogsearch.google.com",
surl:"http://blogsearch.google.com/blogsearch?&ui=blg&q=",
desc:"Search for blogs"},

{id:"aa_googlebookmarks",
type:"google",
cc:"",
name:"googlebookmarks",
label:"google.com/bookmarks",
url:"http://www.google.com/bookmarks",
surl:"http://www.google.com/bookmarks/find?q=",
desc:"Search for your private bookmarks"},

{id:"aa_googlebooks",
type:"google",
cc:"",
name:"googlebooks",
label:"books.google.com",
url:"http://books.google.com",
surl:"http://books.google.com/books?q=",
desc:""},

{id:"aa_googlecodesearch",
type:"google",
cc:"",
name:"googlecodesearch",
label:"google.com/codesearch",
url:"http://www.google.com/codesearch",
surl:"http://www.google.com/codesearch?q=",
desc:""},

{id:"aa_googledirectory",
type:"google",
cc:"",
name:"googledirectory",
label:"directory.google.com",
url:"http://directory.google.com/",
surl:"http://www.google.com/search?hl=en&cat=gwd%2FTop&q=",
desc:""},

{id:"aa_googledocs",
type:"google",
cc:"",
name:"googledocs",
label:"docs.google.com",
url:"http://docs.google.com",
surl:"http://docs.google.com/#search/",
desc:""},

{id:"aa_googlefinance",
type:"google",
cc:"",
name:"googlefinance",
label:"finance.google.com",
url:"http://finance.google.com",
surl:"http://finance.google.com/finance?q=",
desc:""},

{id:"aa_googlegroups",
type:"google",
cc:"",
name:"googlegroups",
label:"groups.google.com",
url:"http://groups.google.com",
surl:"http://groups.google.com/groups/search?q=",
desc:""},

{id:"aa_googlehistory",
type:"google",
cc:"",
name:"googlehistory",
label:"google.com/history",
url:"http://www.google.com/history",
surl:"http://www.google.com/history/find?q=",
desc:""},

{id:"aa_googleimages",
type:"google",
cc:"",
name:"googleimages",
label:"images.google.com",
url:"http://images.google.com",
surl:"http://images.google.com/images?q=",
desc:""},

{id:"aa_googlegadget",
type:"google",
cc:"",
name:"googlegadget",
label:"igoogle gadget directory",
url:"http://www.google.com/ig/directory",
surl:"http://www.google.com/ig/directory?q=",
desc:"Gadget search in iGoogle directory"},

{id:"aa_googlejaiku",
type:"google",
cc:"",
name:"googlejaiku",
label:"jaiku.com",
url:"http://jaiku.com",
surl:"http://jaiku.com/explore/find?query=",
desc:""},

{id:"aa_googleknol",
type:"google",
cc:"",
name:"googleknol",
label:"knol.google.com",
url:"http://knol.google.com",
surl:"http://knol.google.com/k/knol/system/knol/pages/Search?restrict=general&q=",
desc:"A unit of knowledge"},

{id:"aa_googlelinux",
type:"google",
cc:"",
name:"googlelinux",
label:"google.com/linux",
url:"http://www.google.com/linux",
surl:"http://www.google.com/linux?q=",
desc:""},

{id:"aa_googlelively",
type:"google",
cc:"",
name:"googlelively",
label:"lively.com",
url:"http://www.lively.com",
surl:"http://www.lively.com/search?query=",
desc:"Create an avatar and chat with your friends in rooms you design"},

{id:"aa_googlemaps",
type:"google",
cc:"",
name:"googlemaps",
label:"maps.google.com",
url:"http://maps.google.com",
surl:"http://maps.google.com/maps?q=",
desc:""},

{id:"aa_googlenews",
type:"google",
cc:"",
name:"googlenews",
label:"news.google.com",
url:"http://news.google.com",
surl:"http://news.google.com/news?q=",
desc:""},

{id:"aa_googleorkut",
type:"google",
cc:"",
name:"googleorkut",
label:"orkut.com",
url:"http://www.orkut.com",
surl:"http://www.orkut.com/UniversalSearch.aspx?origin=box&exp=1&q=",
desc:""},

{id:"aa_googlepicasa",
type:"google",
cc:"",
name:"googlepicasa",
label:"picasaweb.google.com",
url:"http://picasaweb.google.com",
surl:"http://picasaweb.google.com/lh/searchbrowse?q=",
desc:""},

{id:"aa_googlepatents",
type:"google",
cc:"",
name:"googlepatents",
label:"google.com/patents",
url:"http://www.google.com/patents",
surl:"http://www.google.com/patents?q=",
desc:""},

{id:"aa_googleproducts",
type:"google",
cc:"",
name:"googleproducts",
label:"google.com/products",
url:"http://www.google.com/products",
surl:"http://www.google.com/products?q=",
desc:""},

{id:"aa_googlescholar",
type:"google",
cc:"",
name:"googlescholar",
label:"scholar.google.com",
url:"http://scholar.google.com",
surl:"http://scholar.google.com/scholar?q=",
desc:""},

{id:"aa_googlesites",
type:"google",
cc:"",
name:"googlesites",
label:"sites.google.com",
url:"http://sites.google.com",
surl:"http://sites.google.com/site/sites/system/app/pages/meta/search?q=",
desc:""},

{id:"aa_googletranslate",
type:"google",
cc:"",
name:"googletranslate",
label:"translate.google.com",
url:"http://translate.google.com",
surl:"http://translate.google.com/translate_t#auto|en|",
desc:""},

{id:"aa_googlevideo",
type:"google",
cc:"",
name:"googlevideo",
label:"video.google.com",
url:"http://video.google.com",
surl:"http://video.google.com/videosearch?q=",
desc:""},

{id:"aa_youtube",
type:"google",
cc:"",
name:"youtube",
label:"youtube.com",
url:"http://www.youtube.com",
surl:"http://www.youtube.com/results?search_query=",
desc:""},

{id:"aa_searchmash",
type:"google",
cc:"",
name:"searchmash",
label:"searchmash.com",
url:"http://www.searchmash.com",
surl:"http://www.searchmash.com/search/",
desc:"Spezial Google search engine to test new features."},

{id:"aa_googlemodules",
type:"google",
cc:"",
name:"googlemodules",
label:"googlemodules.com",
url:"http://www.googlemodules.com",
surl:"http://www.googlemodules.com/?mode=showSearchResults&q=",
desc:""},

{id:"aa_gwb",
type:"google",
cc:"",
name:"gwb",
label:"googlewatchblog.de",
url:"http://www.googlewatchblog.de",
surl:"http://www.googlewatchblog.de/index.php?s=",
desc:""},

{id:"aa_live",
type:"portals",
cc:"",
name:"live",
label:"live.com",
url:"http://www.live.com",
surl:"http://search.live.com/results.aspx?q=",
desc:""},

{id:"aa_altavista",
type:"portals",
cc:"",
name:"altavista",
label:"altavista.com",
url:"http://www.altavista.com",
surl:"http://www.altavista.com/web/results?q=",
desc:""},

{id:"aa_ask",
type:"portals",
cc:"",
name:"ask",
label:"ask.com",
url:"http://www.ask.com",
surl:"http://www.ask.com/web?q=",
desc:""},

{id:"aa_yubnub",
type:"portals",
cc:"",
name:"yubnub",
label:"yubnub.org",
url:"http://www.yubnub.org",
surl:"http://yubnub.org/parser/parse?command=",
desc:""},

{id:"aa_a9",
type:"portals",
cc:"",
name:"a9",
label:"a9.com",
url:"http://opensearch.a9.com",
surl:"http://a9.com/?q=",
desc:"search for more at once"},

{id:"aa_wolframalpha",
type:"portals",
cc:"",
name:"wolframalpha",
label:"wolframalpha.com",
url:"http://wolframalpha.com",
surl:"http://wolframalpha.com/input/?",
desc:"computational knowledge engine"},

{id:"aa_snap",
type:"portals",
cc:"",
name:"snap",
label:"snap.com",
url:"http://www.snap.com",
surl:"http://www.snap.com/#",
desc:"The other way to search"},

{id:"aa_kartoo",
type:"portals",
cc:"",
name:"kartoo",
label:"kartoo.com",
url:"http://www.kartoo.com",
surl:"http://www.kartoo.com/flash04.php3?langue=en&q=",
desc:"The other way to search"},

{id:"aa_cuil",
type:"portals",
cc:"",
name:"cuil",
label:"cuil.com",
url:"http://www.cuil.com",
surl:"http://www.cuil.com/search?q=",
desc:"Cuil is an old Irish word for knowledge. For knowledge, ask Cuil."},

{id:"aa_boysfood",
type:"xxx",
cc:"",
name:"boysfood",
label:"boysfood.com",
url:"http://www.boysfood.com",
surl:"http://www.boysfood.com/cgi-bin/bfn.cgi?search=",
desc:""},

{id:"aa_flurl",
type:"xxx",
cc:"",
name:"flurl",
label:"flurl.com",
url:"http://www.flurl.com",
surl:"http://www.flurl.com/search?q=",
desc:""},

{id:"aa_freesextubes",
type:"xxx",
cc:"",
name:"freesextubes",
label:"freesextubes.com",
url:"http://www.freesextubes.com",
surl:"http://www.freesextubes.com/search/",
desc:""},

{id:"aa_kindgirls",
type:"xxx",
cc:"",
name:"kindgirls",
label:"kindgirls.com",
url:"http://kindgirls.com",
surl:"http://kindgirls.com/search.php?s=",
desc:""},

{id:"aa_mrsnake",
type:"xxx",
cc:"",
name:"mrsnake",
label:"mrsnake.com",
url:"http://www.mrsnake.com",
surl:"http://www.mrsnake.com/videos.php?q=",
desc:""},

{id:"aa_pornative",
type:"xxx",
cc:"",
name:"pornative",
label:"pornative.com",
url:"http://www.pornative.com",
surl:"http://www.pornative.com/search/rating/1.html?search=",
desc:""},

{id:"aa_pornhub",
type:"xxx",
cc:"",
name:"pornhub",
label:"pornhub.com",
url:"http://pornhub.com",
surl:"http://www.pornhub.com/video/search?search=",
desc:""},

{id:"aa_pornotube",
type:"xxx",
cc:"",
name:"pornotube",
label:"pornotube.com",
url:"http://pornotube.com",
surl:"http://pornotube.com/search.php?q=",
desc:""},

{id:"aa_redtube",
type:"xxx",
cc:"",
name:"redtube",
label:"redtube.com",
url:"http://www.redtube.com",
surl:"http://www.redtube.com/?search=",
desc:""},

{id:"aa_shufuni",
type:"xxx",
cc:"",
name:"shufuni",
label:"shufuni.com",
url:"http://www.shufuni.com",
surl:"http://www.shufuni.com/SearchResult.aspx?search=",
desc:""},

{id:"aa_thesextubesite",
type:"xxx",
cc:"",
name:"thesextubesite",
label:"thesextubesite.com",
url:"http://www.thesextubesite.com",
surl:"http://www.thesextubesite.com/search/",
desc:""},

{id:"aa_tube8",
type:"xxx",
cc:"",
name:"tube8",
label:"tube8.com",
url:"http://www.tube8.com",
surl:"http://www.tube8.com/search.html?q=",
desc:""},

{id:"aa_vidz",
type:"xxx",
cc:"",
name:"vidz",
label:"vidz.com",
url:"http://www.vidz.com",
surl:"http://www.vidz.com/search?q=",
desc:""},

{id:"aa_xmissyporn",
type:"xxx",
cc:"",
name:"xmissyporn",
label:"xmissyporn.com",
url:"http://www.xmissyporn.com",
surl:"http://www.xmissyporn.com/index.php?amount=0&blogid=9&query=",
desc:""},

{id:"aa_xnxx",
type:"xxx",
cc:"",
name:"xnxx",
label:"xnxx.com",
url:"http://www.xnxx.com",
surl:"http://video.xnxx.com/?k=",
desc:""},

{id:"aa_xtube",
type:"xxx",
cc:"",
name:"xtube",
label:"xtube.com",
url:"http://www.xtube.com",
surl:"http://www.xtube.com/results.php?type=video&search=",
desc:""},

{id:"aa_xvideos",
type:"xxx",
cc:"",
name:"xvideos",
label:"xvideos.com",
url:"http://www.xvideos.com",
surl:"http://www.xvideos.com/?k=",
desc:""},

{id:"aa_youporn",
type:"xxx",
cc:"",
name:"youporn",
label:"youporn.com",
url:"http://www.youporn.com",
surl:"http://youporn.com/search?query=",
desc:""},

{id:"aa_yourfilehost",
type:"xxx",
cc:"",
name:"yourfilehost",
label:"yourfilehost.com",
url:"http://www.yourfilehost.com",
surl:"http://www.flurl.com/search?sort_by=related&site_id=147&q=",
desc:""},

{id:"aa_wikiwix",
type:"knowledge",
cc:"",
name:"wikiwix",
label:"wikiwix.com",
url:"http://www.wikiwix.com",
surl:"http://www.wikiwix.com/index.php?art=true&action=",
desc:"The ultimate Wikipedia articles search engine"},

{id:"aa_wikia",
type:"knowledge",
cc:"",
name:"wikia",
label:"wikia.com",
url:"http://alpha.search.wikia.com",
surl:"http://re.search.wikia.com/search#",
desc:"Search is part of the fundamental infrastructure of the Internet. And we are making it open source"},

{id:"aa_onelook",
type:"knowledge",
cc:"",
name:"onelook",
label:"onelook.com",
url:"http://www.onelook.com",
surl:"http://www.onelook.com/?w=",
desc:"One Click - Multi Dictionary Search"},

{id:"aa_reference",
type:"knowledge",
cc:"",
name:"reference",
label:"reference.com",
url:"http://www.reference.com",
surl:"http://www.reference.com/browse/all/",
desc:""},

{id:"aa_thesaurus",
type:"knowledge",
cc:"",
name:"thesaurus",
label:"thesaurus.com",
url:"http://www.thesaurus.com",
surl:"http://thesaurus.reference.com/browse/",
desc:""},

{id:"aa_dictionary",
type:"knowledge",
cc:"",
name:"dictionary",
label:"dictionary.com",
url:"http://www.dictionary.com",
surl:"http://dictionary.reference.com/browse/",
desc:""},

{id:"aa_archive",
type:"knowledge",
cc:"",
name:"archive",
label:"archive.org",
url:"http://www.archive.org",
surl:"http://www.archive.org/search.php?query=",
desc:"Universal Access to human knowledge"},

{id:"aa_waybackmachine",
type:"knowledge",
cc:"",
name:"waybackmachine",
label:"WayBackMachine",
url:"http://web.archive.org/collections/web.html",
surl:"http://web.archive.org/archive_request_ng?url=",
desc:"Surf the web as it was"},

{id:"aa_myspace",
type:"community",
cc:"",
name:"myspace",
label:"myspace.com",
url:"http://www.myspace.com",
surl:"http://searchservice.myspace.com/index.cfm?fuseaction=search&searchType=network&searchBy=First&Submit=Suchen&SearchBoxID=FindAFriend&f_first_name=",
desc:""},

{id:"aa_facebook",
type:"community",
cc:"",
name:"facebook",
label:"facebook.com",
url:"http://www.facebook.com",
surl:"http://www.facebook.com/srch.php?nm=",
desc:"Facebook is a social utility that connects you with the people around you."},

{id:"aa_linkedin",
type:"community",
cc:"",
name:"linkedin",
label:"linkedin.com",
url:"http://www.linkedin.com",
surl:"http://www.linkedin.com/search?search=&sortCriteria=4&rd=out&keywords=",
desc:"Share knowledge and tap into relationships."},

{id:"aa_hi5",
type:"community",
cc:"",
name:"hi5",
label:"hi5.com",
url:"http://www.hi5.com",
surl:"http://hi5.com/friend/processBrowseSearch.do?searchText=",
desc:"Discover, Connect, Communicate"},

{id:"aa_wayn",
type:"community",
cc:"",
name:"wayn",
label:"wayn.com",
url:"http://www.wayn.com",
surl:"http://www.wayn.com/waynsearches.html?wci=namesearchresults&country=All%20Countries&forename=&surname=",
desc:"Where are you now?"},

{id:"aa_classmates",
type:"community",
cc:"",
name:"classmates",
label:"classmates.com",
url:"http://www.classmates.com",
surl:"http://www.classmates.com/search/mastheadSearch.do?queryString=",
desc:"Real people, real names."},

{id:"aa_twitter",
type:"community",
cc:"",
name:"twitter",
label:"twitter.com",
url:"http://twitter.com",
surl:"http://search.twitter.com/search?q=",
desc:"See what's happening — right now."},

{id:"aa_digg",
type:"bookmarking",
cc:"",
name:"digg",
label:"digg.com",
url:"http://digg.com",
surl:"http://digg.com/search?section=all&s=",
desc:""},

{id:"aa_delicious",
type:"bookmarking",
cc:"",
name:"delicious",
label:"del.icio.us",
url:"http://del.icio.us",
surl:"http://del.icio.us/search/?fr=del_icio_us&type=all&p=",
desc:""},

{id:"aa_reddit",
type:"bookmarking",
cc:"",
name:"reddit",
label:"reddit.com",
url:"http://reddit.com",
surl:"http://reddit.com/search?q=",
desc:""},

{id:"aa_flickr",
type:"media",
cc:"",
name:"flickr",
label:"flickr.com",
url:"http://flickr.com",
surl:"http://flickr.com/search/?q=",
desc:""},

{id:"aa_hulu",
type:"media",
cc:"",
name:"hulu",
label:"hulu.com",
url:"http://hulu.com",
surl:"http://www.hulu.com/videos/search?query=",
desc:""},

{id:"aa_brightcove",
type:"media",
cc:"",
name:"brightcove",
label:"brightcove.com",
url:"http://www.brightcove.com",
surl:"http://www.brightcove.com/search/search.cfm?cx=011043846403879487989%3Aoa7iaakkyzm&cof=FORID%3A11%3BNB%3A1&q=",
desc:""},

{id:"aa_livevideo",
type:"media",
cc:"",
name:"livevideo",
label:"livevideo.com",
url:"http://www.livevideo.com",
surl:"http://www.livevideo.com/media/search.aspx?d=1&tag=",
desc:""},

{id:"aa_purevideo",
type:"media",
cc:"",
name:"purevideo",
label:"purevideo.com",
url:"http://www.purevideo.com",
surl:"http://www.purevideo.com/video-",
desc:"First Internet Video Meta Search"},

{id:"aa_imdb",
type:"media",
cc:"",
name:"imdb",
label:"imdb.com",
url:"http://www.imdb.com",
surl:"http://www.imdb.com/find?q=",
desc:""},

{id:"aa_yahoovideo",
type:"media",
cc:"",
name:"yahoovideo",
label:"video.yahoo.com",
url:"http://video.yahoo.com",
surl:"http://video.yahoo.com/video/search?p=",
desc:"",
icon:"yahoo"},

{id:"aa_photobucket",
type:"media",
cc:"",
name:"photobucket",
label:"photobucket.com",
url:"http://photobucket.com",
surl:"http://photobucket.com/images/",
desc:""},

{id:"aa_dailymotion",
type:"media",
cc:"",
name:"dailymotion",
label:"dailymotion.com",
url:"http://www.dailymotion.com",
surl:"http://www.dailymotion.com/videos/relevance/search/",
desc:""},

{id:"aa_megavideo",
type:"media",
cc:"",
name:"megavideo",
label:"megavideo.com",
url:"http://www.megavideo.com",
surl:"http://www.megavideo.com/?c=search&s=",
desc:""},

{id:"aa_videojug",
type:"media",
cc:"",
name:"videojug",
label:"videojug.com",
url:"http://www.videojug.com",
surl:"http://www.videojug.com/search?keywords=",
desc:""},

{id:"aa_teachertube",
type:"media",
cc:"",
name:"teachertube",
label:"teachertube.com",
url:"http://www.teachertube.com",
surl:"http://www.teachertube.com/search_result.php?search_id=",
desc:"Teach the world"},

{id:"aa_metacafe",
type:"media",
cc:"",
name:"metacafe",
label:"metacafe.com",
url:"http://www.metacafe.com",
surl:"http://www.metacafe.com/tags/",
desc:""},

{id:"aa_heavy",
type:"media",
cc:"",
name:"heavy",
label:"heavy.com",
url:"http://www.heavy.com",
surl:"http://www.heavy.com/search?action=videos&tag=",
desc:""},

{id:"aa_alluc",
type:"media",
cc:"",
name:"alluc",
label:"alluc.org",
url:"http://www.alluc.org",
surl:"http://www12.alluc.org/alluc/no_cache/results.html?tx_ansearchit_resOverview%5Bsection%5D=3.&tx_ansearchit_resOverview%5BsWord%5D=",
desc:""},

{id:"aa_fanpop",
type:"media",
cc:"",
name:"fanpop",
label:"fanpop.com",
url:"http://www.fanpop.com",
surl:"http://www.fanpop.com/search/",
desc:""},

{id:"aa_php",
type:"programming",
cc:"",
name:"php",
label:"php.net",
url:"http://www.php.net",
surl:"http://de3.php.net/manual-lookup.php?lang=de&pattern=",
desc:""},

{id:"aa_msdn",
type:"programming",
cc:"",
name:"msdn",
label:"msdn.com",
url:"http://www.msdn.microsoft.com",
surl:"http://search.msdn.microsoft.com/search/default.aspx?query=",
desc:""},

{id:"aa_sourceforge",
type:"programming",
cc:"",
name:"sourceforge",
label:"sourceforge.net",
url:"http://www.sourceforge.net",
surl:"http://sourceforge.net/search/?type_of_search=soft&words=",
desc:""},

{id:"aa_apidoc",
type:"programming",
cc:"",
name:"apidoc",
label:"apidoc.org",
url:"http://apidoc.org",
surl:"http://apidoc.org/search?q=",
desc:""},

{id:"aa_ruby",
type:"programming",
cc:"",
name:"ruby",
label:"ruby-lang.org",
url:"http://www.ruby-lang.org/en/",
surl:"http://www.ruby-lang.org/en/search/?q=",
desc:"ruby official"},

{id:"aa_krugle",
type:"programming",
cc:"",
name:"krugle",
label:"krugle.com",
url:"http://krugle.com",
surl:"http://krugle.com/kse/files?query=",
desc:">>> find code"},

{id:"aa_koders",
type:"programming",
cc:"",
name:"koders",
label:"koders.com",
url:"http://www.koders.com",
surl:"http://www.koders.com/default.aspx?s=",
desc:""},

{id:"aa_perldoc",
type:"programming",
cc:"",
name:"perldoc",
label:"perldoc.perl.org",
url:"http://perldoc.perl.org",
surl:"http://perldoc.perl.org/search.html?q=",
desc:""},

{id:"aa_perlmonks",
type:"programming",
cc:"",
name:"perlmonks",
label:"perlmonks.org",
url:"http://www.perlmonks.org",
surl:"http://www.perlmonks.org/?node=",
desc:""},

{id:"aa_portableapps",
type:"programming",
cc:"",
name:"portableapps",
label:"portableapps.com",
url:"http://www.portableapps.com",
surl:"http://portableapps.com/search/node/",
desc:""},

{id:"aa_ajaxrain",
type:"programming",
cc:"",
name:"ajaxrain",
label:"ajaxrain.com",
url:"http://www.ajaxrain.com",
surl:"http://www.ajaxrain.com/search.php?seVal=",
desc:"JS libs"},

{id:"aa_torrentsearchbar",
type:"torrent",
cc:"",
name:"torrentsearchbar",
label:"torrent-search-bar.com",
url:"http://www.torrent-search-bar.com",
surl:"http://www.google.com/custom?cx=007543263361953292879%3Aip0b-z8nzwc&sa=Search&cof=GFNT%3A%23000000%3BGALT%3A%23008000%3BLH%3A51%3BCX%3ATorrent%2520Search%3BVLC%3A%23663399%3BDIV%3A%23FFFFFF%3BFORID%3A1%3BT%3A%23000000%3BALC%3A%230000CC%3BLC%3A%230000CC%3BS%3Ahttp%3A%2F%2Fwww%2Etorrent-search-bar%2Ecom%2F%3BL%3Ahttp%3A%2F%2Fwww%2Etorrent-search-bar%2Ecom%2Ftorrent_search_logo_s%2Egif%3BGIMP%3A%23000000%3BLP%3A1%3BBGC%3A%23FFFFFF%3BAH%3Aleft&client=pub-4359655221859943&q=",
desc:""},

{id:"aa_torrentsbooth",
type:"torrent",
cc:"",
name:"torrentsbooth",
label:"torrentsbooth.com",
url:"http://www.torrentsbooth.com",
surl:"http://www.torrentsbooth.com/torrentsearch.html?cx=003343599837851107519%3Ad8dqv2x7u-8&cof=FORID%3A10&q=",
desc:""},

{id:"aa_torrentportal",
type:"torrent",
cc:"",
name:"torrentportal",
label:"torrentportal.com",
url:"http://www.torrentportal.com",
surl:"http://www.torrentportal.com/torrents-search.php?search=",
desc:""},

{id:"aa_torrentscoop",
type:"torrent",
cc:"",
name:"torrentscoop",
label:"torrentscoop.com",
url:"http://torrentscoop.com",
surl:"http://torrentscoop.com/results.php?google_ad_client=&cx=004204163392280045974%3A6_k16oycl5e&cof=FORID%3A10&q=",
desc:""},

{id:"aa_torrent-finder",
type:"torrent",
cc:"",
name:"torrent-finder",
label:"torrent-finder.com",
url:"http://www.torrent-finder.com",
surl:"http://torrent-finder.com/show.php?Search=Search&PageLoad=oneattime&select=ALL&kywrd=",
desc:""},

{id:"aa_btjunkie",
type:"torrent",
cc:"",
name:"btjunkie",
label:"btjunkie.org",
url:"http://www.btjunkie.org",
surl:"http://btjunkie.org/search?q=",
desc:""},

{id:"aa_isohunt",
type:"torrent",
cc:"",
name:"isohunt",
label:"isohunt.com",
url:"http://www.isohunt.com",
surl:"http://www.isohunt.com/torrents/",
desc:""},

{id:"aa_mininova",
type:"torrent",
cc:"",
name:"mininova",
label:"mininova.org",
url:"http://www.mininova.org",
surl:"http://www.mininova.org/search/?search=",
desc:""},

{id:"aa_meganova",
type:"torrent",
cc:"",
name:"meganova",
label:"meganova.org",
url:"http://www.meganova.org",
surl:"http://www.meganova.org/search.php?order=5&search=",
desc:""},

{id:"aa_thepiratebay",
type:"torrent",
cc:"",
name:"thepiratebay",
label:"thepiratebay.org",
url:"http://www.thepiratebay.org",
surl:"http://thepiratebay.org/search.php?orderby=se&q=",
desc:""},

{id:"aa_torrentspy",
type:"torrent",
cc:"",
name:"torrentspy",
label:"torrentspy.com",
url:"http://www.torrentspy.com",
surl:"http://www.torrentspy.com/search?query=",
desc:""},

{id:"aa_yabse",
type:"torrent",
cc:"",
name:"yabse",
label:"yabse.com",
url:"http://yabse.com",
surl:"http://yabse.com/index.php?q=",
desc:""},

{id:"aa_ign",
type:"games",
cc:"",
name:"ign",
label:"ign.com",
url:"http://www.ign.com",
surl:"http://search.ign.com/products?query=",
desc:""},

{id:"aa_gamespot",
type:"games",
cc:"",
name:"gamespot",
label:"gamespot.com",
url:"http://www.gamespot.com",
surl:"http://www.gamespot.com/search.html?type=11&stype=all&tag=search%3Bbutton&qs=",
desc:""},

{id:"aa_gamefaqs",
type:"games",
cc:"",
name:"gamefaqs",
label:"gamefaqs.com",
url:"http://www.gamefaqs.com",
surl:"http://www.gamefaqs.com/search/index.html?game=",
desc:""},

{id:"aa_gamerankings",
type:"games",
cc:"",
name:"gamerankings",
label:"gamerankings.com",
url:"http://www.gamerankings.com",
surl:"http://www.gamerankings.com/itemrankings/simpleratings.asp?itemname=",
desc:""},

{id:"aa_thottbot",
type:"wow",
cc:"",
name:"thottbot",
label:"thottbot.com",
url:"http://www.thottbot.com",
surl:"http://www.thottbot.com/?s=",
desc:""},

{id:"aa_allakhazam",
type:"wow",
cc:"",
name:"allakhazam",
label:"allakhazam.com",
url:"http://www.allakhazam.com",
surl:"http://wow.allakhazam.com/search.html?q=",
desc:""},

{id:"aa_wowhead",
type:"wow",
cc:"",
name:"wowhead",
label:"wowhead.com",
url:"http://www.wowhead.com",
surl:"http://www.wowhead.com/?search=",
desc:""},

{id:"aa_goblinworkshop",
type:"wow",
cc:"",
name:"goblinworkshop",
label:"goblinworkshop.com",
url:"http://www.goblinworkshop.com",
surl:"http://www.goblinworkshop.com/search2.html?s=",
desc:""},

{id:"aa_wowguru",
type:"wow",
cc:"",
name:"wowguru",
label:"wowguru.com",
url:"http://www.wowguru.com",
surl:"http://www.wowguru.com/db/search.php?q=",
desc:""},

{id:"aa_warcry",
type:"wow",
cc:"",
name:"warcry",
label:"warcry.com",
url:"http://www.warcry.com",
surl:"http://wow.warcry.com/db/search.php?sh=",
desc:""}

];